baseurl = "https://www.equinetech.org/dict"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "etg data dictionary"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  # editURL = ""
  description = ""
  author = ""
  showVisitedLinks = false
  themeVariant = "mine"
  disableSearch = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = ""
weight = 1
languageName = "English"
